version: "3.1"

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - monitoring
    volumes:
      - grafana_etc:/etc/grafana
      - grafana_lib:/var/lib/grafana
      - grafana_log:/var/log/grafana
    deploy:
      placement:
        constraints: [node.labels.node-role == infra]
    labels:
      container-type: "monitoring"

networks:
    monitoring:
      external:
        name: monitoring

volumes:
    grafana_etc:
    grafana_lib:
    grafana_log:
    