version: "3.1"

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - monitoring
    volumes:
      - /root/git/grafana-data/etc:/etc/grafana
      - /root/git/grafana-data/lib:/var/lib/grafana
      - /root/git/grafana-data/log:/var/log/grafana
    deploy:
      placement:
        constraints: [node.labels.node-role == infra]
    labels:
      container-type: "monitoring"

networks:
    monitoring:
      external:
        name: monitoring